language: 'python'

python:
  - '3.5.2'

install:
  - pip install -r requirements.txt

env:
  - DB = postgres USER = postgres PASSWORD = 'python'

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres

script:
  - pytest -v --cov=app/api
  - coveralls

after_success:
  - coveralls
